"""initial_schema

Revision ID: 18657912267e
Revises:
Create Date: 2026-07-22 15:35:19.900101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18657912267e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_events_event_type'), 'bot_events', ['event_type'], unique=False)
    op.create_table('bot_runtime_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_status', sa.String(length=32), nullable=False),
    sa.Column('emergency_stop', sa.Boolean(), nullable=False),
    sa.Column('execution_mode', sa.String(length=16), nullable=False),
    sa.Column('auto_trading_enabled', sa.Boolean(), nullable=False),
    sa.Column('risk_per_trade', sa.Float(), nullable=False),
    sa.Column('leverage_cap', sa.Float(), nullable=False),
    sa.Column('exposure_cap', sa.Float(), nullable=False),
    sa.Column('max_open_trades', sa.Integer(), nullable=False),
    sa.Column('max_daily_trades', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_authority_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumed_risk_approvals',
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_consumed_risk_approvals_decision_id'), 'consumed_risk_approvals', ['decision_id'], unique=False)
    op.create_table('risk_runtime_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trades_day', sa.String(length=10), nullable=True),
    sa.Column('trades_today', sa.Integer(), nullable=False),
    sa.Column('active_symbols', sa.Text(), nullable=False),
    sa.Column('active_trade_count', sa.Integer(), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('symbol_cooldowns', sa.Text(), nullable=False),
    sa.Column('day_start_equity', sa.Float(), nullable=True),
    sa.Column('realized_pnl_today', sa.Float(), nullable=False),
    sa.Column('live_risk', sa.Float(), nullable=False),
    sa.Column('base_risk_pool', sa.Float(), nullable=False),
    sa.Column('effective_risk_pool', sa.Float(), nullable=False),
    sa.Column('available_risk', sa.Float(), nullable=False),
    sa.Column('circuit_breaker_active', sa.Boolean(), nullable=False),
    sa.Column('circuit_breaker_reason', sa.String(length=255), nullable=True),
    sa.Column('audit_evidence_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scanner_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger_source', sa.String(length=32), nullable=False),
    sa.Column('symbols_scanned', sa.Integer(), nullable=False),
    sa.Column('signals_found', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('warning_error_count', sa.Integer(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('scanner_config_version', sa.String(length=128), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanner_snapshots_scan_id'), 'scanner_snapshots', ['scan_id'], unique=True)
    op.create_table('trade_journal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journal_id', sa.String(length=64), nullable=False),
    sa.Column('execution_key', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('execution_mode', sa.String(length=16), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('strategy_name', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('sl_hit_reason', sa.String(length=64), nullable=True),
    sa.Column('close_reason', sa.String(length=64), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('order_id', sa.String(length=128), nullable=True),
    sa.Column('detected_at', sa.String(length=64), nullable=True),
    sa.Column('opened_at', sa.String(length=64), nullable=True),
    sa.Column('closed_at', sa.String(length=64), nullable=True),
    sa.Column('exchange_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_journal_execution_key'), 'trade_journal', ['execution_key'], unique=True)
    op.create_index(op.f('ix_trade_journal_journal_id'), 'trade_journal', ['journal_id'], unique=True)
    op.create_index(op.f('ix_trade_journal_symbol'), 'trade_journal', ['symbol'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('token_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_id'), 'user_sessions', ['token_id'], unique=True)
    op.create_index(op.f('ix_user_sessions_username'), 'user_sessions', ['username'], unique=False)
    op.create_table('watchdog_runtime_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('action_mode', sa.String(length=24), nullable=False),
    sa.Column('mismatch_tolerance_cycles', sa.Integer(), nullable=False),
    sa.Column('exposure_tolerance_ratio', sa.Float(), nullable=False),
    sa.Column('pnl_tolerance', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('execution_blocked', sa.Boolean(), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=False),
    sa.Column('consecutive_mismatch_cycles', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_snapshot_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchdog_runtime_state')
    op.drop_index(op.f('ix_user_sessions_username'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_trade_journal_symbol'), table_name='trade_journal')
    op.drop_index(op.f('ix_trade_journal_journal_id'), table_name='trade_journal')
    op.drop_index(op.f('ix_trade_journal_execution_key'), table_name='trade_journal')
    op.drop_table('trade_journal')
    op.drop_index(op.f('ix_scanner_snapshots_scan_id'), table_name='scanner_snapshots')
    op.drop_table('scanner_snapshots')
    op.drop_table('risk_runtime_state')
    op.drop_index(op.f('ix_consumed_risk_approvals_decision_id'), table_name='consumed_risk_approvals')
    op.drop_table('consumed_risk_approvals')
    op.drop_table('config_authority_state')
    op.drop_table('bot_runtime_config')
    op.drop_index(op.f('ix_bot_events_event_type'), table_name='bot_events')
    op.drop_table('bot_events')
    # ### end Alembic commands ###
